export const discoverCards = [
    {
        link: "./images/gallery/img 116.jpg",
        splash: "art",
        name: "Amazing javascript",
        avatar: "./images/profile_1.png",
        price: "2.45",
        priceInfo: "3 in stock",
        cardBid: "0.085 ETH",
        prop: "art",
    },
    {
        link: "./images/gallery/img 109.jpg",
        splash: "art",
        name: "Amazing javascript",
        avatar: "./images/profile_1.png",
        price: "2.45",
        priceInfo: "3 in stock",
        cardBid: "0.085 ETH",
        prop: "art",
    },
    {
        link: "./images/gallery/img 108.jpg",
        splash: "game",
        name: "Amazing javascript",
        avatar: "./images/profile_1.png",
        price: "2.45",
        priceInfo: "3 in stock",
        cardBid: "0.085 ETH",
        prop: "game",
    },
    {
        link: "./images/gallery/img 110.jpg",
        splash: "game",
        name: "Amazing javascript",
        avatar: "./images/profile_1.png",
        price: "2.45",
        priceInfo: "3 in stock",
        cardBid: "0.085 ETH",
        prop: "game",
    },
    {
        link: "./images/gallery/img 101.png",
        splash: "art",
        name: "Amazing javascript",
        avatar: "./images/profile_1.png",
        price: "2.45",
        priceInfo: "3 in stock",
        cardBid: "0.085 ETH",
        prop: "art",
    },
    {
        link: "./images/gallery/img 103.png",
        splash: "music",
        name: "Amazing javascript",
        avatar: "./images/profile_1.png",
        price: "2.45",
        priceInfo: "3 in stock",
        cardBid: "0.085 ETH",
        prop: "music",
    },
    {
        link: "./images/gallery/img 126.jpg",
        splash: "music",
        name: "Amazing javascript",
        avatar: "./images/profile_1.png",
        price: "2.45",
        priceInfo: "3 in stock",
        cardBid: "0.085 ETH",
        prop: "music",
    },
    {
        link: "./images/gallery/img 127.jpg",
        splash: "video",
        name: "Amazing javascript",
        avatar: "./images/profile_1.png",
        price: "2.45",
        priceInfo: "3 in stock",
        cardBid: "0.085 ETH",
        prop: "video",
    },
    {
        link: "./images/gallery/img 115.png",
        splash: "video",
        name: "Amazing javascript",
        avatar: "./images/profile_1.png",
        price: "2.45",
        priceInfo: "3 in stock",
        cardBid: "0.085 ETH",
        prop: "video",
    },
    {
        link: "./images/gallery/img 114.png",
        splash: "photography",
        name: "Amazing javascript",
        avatar: "./images/profile_1.png",
        price: "2.45",
        priceInfo: "3 in stock",
        cardBid: "0.085 ETH",
        prop: "photography",
    },
    {
        link: "./images/gallery/img 133.png",
        splash: "photography",
        name: "Amazing javascript",
        avatar: "./images/profile_1.png",
        price: "2.45",
        priceInfo: "3 in stock",
        cardBid: "0.085 ETH",
        prop: "photography",
    },
    {
        link: "./images/gallery/img 120.jpg",
        splash: "photography",
        name: "Amazing javascript",
        avatar: "./images/profile_1.png",
        price: "2.45",
        priceInfo: "3 in stock",
        cardBid: "0.085 ETH",
        prop: "photography",
    },
];